twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        permissionService: '@App\StudWorks\Config\Twig\Provider\GlobalVariablesProvider'